name: Waka Readme

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TOTAL: true
          CODE_LANG: python
          IGNORED_LANGUAGES: YAML JSON TOML Binary plaintext Markdown
          
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
